In [1]:
import numpy as np

In [2]:
#program3-c2
print("checkereboard pattern:") 
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

checkereboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
#program4-c2
a1=np.array([5,3,8,2,1])
print(a1)
a2=np.array([3,2,1])
print(a2)
print(":",np.in1d(a1,a2))

[5 3 8 2 1]
[3 2 1]
common elements: [False  True False  True  True]


In [6]:
#program5-c2
a1=np.array([5,3,8,2,1])
print(a1)
a2=np.array([3,2,1])
print(a2)
print("common elements:",np.intersect1d(a1,a2))
print("union of arrays:",np.union1d(a1,a2))

[5 3 8 2 1]
[3 2 1]
common elements: [1 2 3]
union of arrays: [1 2 3 5 8]


In [7]:
#program6-c2
a3=np.array([1,1,2,2,2,3,4,5,5])
print(a3)
print("unique elements:",np.unique(a3))

[1 1 2 2 2 3 4 5 5]
unique elements: [1 2 3 4 5]


In [12]:
#program7-c2
a4=np.array([2,4,6,8,10])
print("array:",a4)
print("type:",type(a4))
l1=a4.tolist()
print(l1)
print("type:",type(l1))

array: [ 2  4  6  8 10]
type: <class 'numpy.ndarray'>
[2, 4, 6, 8, 10]
type: <class 'list'>


In [21]:
#checkerboard pattern-q12
print("checkereboard pattern:") 
b=np.zeros((8,8),dtype=int)
b[::2,4::]=1
b[1::2,:4:]=1
print(b)

checkereboard pattern:
[[0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]]


In [27]:
#sample
print("checkereboard pattern:") 
j=np.zeros((8,8),dtype=int)
j[::2,:2:]=1
j[::2,4:6:]=1
j[1::2,2:4:]=1
j[1::2,6::]=1
print(j)

checkereboard pattern:
[[1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]]


In [ ]:
#checkerboard pattern-q13

In [37]:
import numpy as np
print("checkerboard pattern:") 
z=np.zeros((8,8),dtype=int)
z[::2,:2:]=1
z[::2,4:6:]=1
z[1::2,2:4:]=1
z[1::3,6::]=1
z[2:5:2,6::]=1
z[3:6:2,2:6:]=1
z[2:5:2,2:6:]=0
print(z)

checkerboard pattern:
[[1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]]


In [14]:
#program-8
#acces array by column
import numpy as np
a1=np.array([[1,3,5],[2,4,9]]) 
print(a1)
print("first column:",a1[:,0])
print("second column:",a1[:,1])
print("third column:",a1[:,2])

[[1 3 5]
 [2 4 9]]
first column: [1 2]
second column: [3 4]
third column: [5 9]


In [41]:
#program-9
#matrix multiplication and addition
import numpy as np
m1=np.array([[1,8,3],[2,5,7],[9,4,6]])
m2=np.array([[5,1,4],[2,8,9],[7,3,6]])
print("matrix1:")
print(m1)
print("matrix2:")
print(m2)
print("product of matrices:")
print(np.dot(m1,m2))
print("sum of matrices:")
print(np.add(m1,m2))

matrix1:
[[1 8 3]
 [2 5 7]
 [9 4 6]]
matrix2:
[[5 1 4]
 [2 8 9]
 [7 3 6]]
product of matrices:
[[ 42  74  94]
 [ 69  63  95]
 [ 95  59 108]]
sum of matrices:
[[ 6  9  7]
 [ 4 13 16]
 [16  7 12]]


In [28]:
#program-10
#eigen values and eigen vectors
import numpy as np
q=np.array([[4,2],[7,2]]) 
print("matrix:")
print(q) 
w,v=np.linalg.eig(q)
print("eigen values:",w)
print("eigen vectors:")
print(v)

matrix:
[[4 2]
 [7 2]]
eigen values: [ 6.87298335 -0.87298335]
eigen vectors:
[[ 0.57133452 -0.37969079]
 [ 0.82071729  0.92511345]]


In [35]:
#program-11
#transpose,determinant,inverse of matrix 
import numpy as np
m=np.array([[3,8],[5,7]])
print(m)
print("transpose:")
print(np.transpose(m))
print("determinant:",np.linalg.det(m))
print("inverse:")
print(np.linalg.inv(m))

[[3 8]
 [5 7]]
transpose:
[[3 5]
 [8 7]]
determinant: -18.999999999999996
inverse:
[[-0.36842105  0.42105263]
 [ 0.26315789 -0.15789474]]
